---
apiVersion: v1
kind: Namespace
metadata:
  name: ng-app

---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: ng-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: ng-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:15.1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "123456"
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -d
                - db_prod
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -d
                - db_prod
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ng-app
spec:
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ng-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: dheeraj7444/ng_backend:1
          ports:
            - containerPort: 3001
          env:
            - name: APP_PORT
              value: "3001"
            - name: JWT_SECRET
              value: "jwt_secret"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASS
              value: "123456"
            - name: DB_HOST
              value: "db"
            - name: DB_PORT
              value: "5432"
          livenessProbe:
            tcpSocket:
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ng-app
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000
  selector:
    app: frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ng-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: dheeraj7444/ng_frontend:1
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://backend:3001"
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
